[package]
name = "timely-affinity"
version = "0.1.0"
authors = ["Andrea Lattuada <andrea.lattuada@inf.ethz.ch>"]

[dependencies]
getopts = { version = "0.2.14" }
timely_logging = { git = "https://github.com/frankmcsherry/timely-dataflow", rev = "c3d0a44a60004ddc93ede38b38abd0015c1e843d" }
timely_communication = { git = "https://github.com/frankmcsherry/timely-dataflow" , rev = "c3d0a44a60004ddc93ede38b38abd0015c1e843d" }
timely = { git = "https://github.com/frankmcsherry/timely-dataflow", rev = "c3d0a44a60004ddc93ede38b38abd0015c1e843d" }
libc = "^0.2"
