[package]
name = "timely-affinity"
version = "0.1.0"
authors = ["Andrea Lattuada <andrea.lattuada@inf.ethz.ch>"]

[dependencies]
getopts = { version = "0.2.14" }
timely_logging = { git = "https://github.com/frankmcsherry/timely-dataflow", rev = "75fe42ad3d566de3a32af6dff2ca042fd9e45f61" }
timely_communication = { git = "https://github.com/frankmcsherry/timely-dataflow" , rev = "75fe42ad3d566de3a32af6dff2ca042fd9e45f61" }
timely = { git = "https://github.com/frankmcsherry/timely-dataflow", rev = "75fe42ad3d566de3a32af6dff2ca042fd9e45f61" }
libc = "^0.2"
